spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/aran-test?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
